site_name: Architecture Diagram Sample
site_url: https://cmayor.github.io/structurizer-test/

plugins:
    - search
    - macros
    - mermaid2:
          arguments:
              securityLevel: 'loose'

    - build_plantuml:
          render: 'server' # or "local" for local rendering
          server: 'http://www.plantuml.com/plantuml' # offical plantuml server
          disable_ssl_certificate_validation: true # for self-signed and invalid certs
          output_format: 'svg' # or "png"
          diagram_root: 'docs/diagrams' # should reside under docs_dir
          output_folder: 'out'
          input_folder: 'src'
          input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed

theme:
    name: material